spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: isuru_kavi
    password: isuru_kavi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-decription: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


server:
  port: 8050